name: conda
on: [push]
jobs:
  constructor:
    name: conda build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}-latest
    defaults:
      run:
        shell: ${{ matrix.shell }}
    strategy:
      matrix:
        os: [ubuntu, windows, macos]
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
        include:
          - os: ubuntu
            shell: bash -l {0}
          - os: windows
            shell: cmd /C call {0}
          - os: macos
            shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          miniforge-variant: Mambaforge
          miniforge-version: latest
          mamba-version: "*"
          use-mamba: true
          python-version: ${{ matrix.python-version }}
      - name: constructor build
        run: constructor --output-dir dist/main .
      - name: Pyinstaller
        run: |
          pyinstaller --onefile --clean --name "installer-${{ matrix.os }}-${{ matrix.python-version}}" --distpath dist/main src/science/main.py
      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: installer-${{ matrix.os }}${{ matrix.python-version}}
      #     path: dist/main/**/*
      - uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: dist/main/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is  
        
