name: conda
on: [push]
jobs:
  constructor:
    name: conda build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          miniforge-variant: Mambaforge
          miniforge-version: latest
          mamba-version: "*"
          use-mamba: true
          python-version: ${{ matrix.python-version }}
      - name: constructor build
        run: constructor --output-dir dist/main
      - name: Pyinstaller
        run: |
          pyinstaller --onefile --clean --name "installer-${{ matrix.os }}${{ matrix.python-version}}" --distpath dist/main src/main.py
      - uses: actions/upload-artifact@v3
        with:
          name: installer-${{ matrix.os }}${{ matrix.python-version}}
          path: dist/main/**/*
        
        
